// Supabase Edge Function: intake  (Deno runtime) — the AI Inbox's way in (ADR-0023).
//
// A person opened a mail in Gmail and pressed "Send to ERP → Sales Order" (or uploaded a document in the AI Inbox). This function reads
// the document with Gemini, matches it against the company's masters and puts a PROPOSAL in the inbox. It posts nothing: a person
// accepts the proposal in the voucher window. The document lives only for the request; it is never stored and never logged.
//
// The logic lives in ./handler.bundle.js — a self-contained build of the domain, adapter-postgres and adapter-gemini
// (`pnpm build:functions`). This file is only the Deno glue.
//
// Environment:
//   SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, SUPABASE_DB_URL   provided by Supabase
//   GEMINI_API_KEY    an API key from Google AI Studio (free tier works)   supabase secrets set GEMINI_API_KEY=…
//   GEMINI_MODEL      the model(s) to read with, in order, comma-separated: a busy one hands over to the next
//                     supabase secrets set GEMINI_MODEL=gemini-3.6-flash,gemini-3.8-flash,…
//                     (the free tier allows ~20 readings a day PER MODEL; an alias like gemini-flash-latest shares its model's quota)

import { createClient } from '@supabase/supabase-js';
import postgres from 'postgres';
// @ts-expect-error — generated by `pnpm build:functions`; no type declarations
import { GeminiReader, PostgresBackend, createIntakeHandler } from './handler.bundle.js';

const sql = postgres(Deno.env.get('SUPABASE_DB_URL')!, { max: 1, prepare: false });
const db = {
  query: async (text: string, values: readonly unknown[] = []) => ({
    rows: (await sql.unsafe(text, values as never[])) as unknown as Record<string, unknown>[],
  }),
};

const admin = createClient(Deno.env.get('SUPABASE_URL')!, Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!, {
  auth: { persistSession: false },
});

const apiKey = Deno.env.get('GEMINI_API_KEY');
const model = Deno.env.get('GEMINI_MODEL');

Deno.serve(
  createIntakeHandler({
    async authenticate(request: Request) {
      const token = request.headers.get('Authorization')?.replace(/^Bearer\s+/i, '');
      if (!token) return undefined;
      const { data, error } = await admin.auth.getUser(token);
      return error || !data.user ? undefined : { userId: data.user.id };
    },
    gatewayFor: (actorId: string, requestId: string) => new PostgresBackend(db, { actorId, requestId }),
    reader:
      apiKey && model
        ? // A background reading: the models in turn, round after round 8 s apart, for up to ~100 s (the function may run ~150 s).
          new GeminiReader({ apiKey, model, timeoutMs: 40_000, rounds: 10, retryDelayMs: 8_000, deadlineMs: 100_000 })
        : { read: async () => ({ ok: false, issues: [{ code: 'READER_NOT_SET_UP', message: 'Gemini is not set up: GEMINI_API_KEY and GEMINI_MODEL are needed' }] }) },
    // the reading continues after the panel has its answer
    defer: (work: Promise<unknown>) => (globalThis as unknown as { EdgeRuntime: { waitUntil(p: Promise<unknown>): void } }).EdgeRuntime.waitUntil(work),
    // the error only — never the request body, which holds the document
    onError: (error: unknown, requestId: string) =>
      console.error(JSON.stringify({ level: 'error', requestId, error: String(error), stack: (error as Error)?.stack })),
  }),
);
