// Supabase Edge Function: assistant  (Deno runtime) — the floating assistant in the ERP (v1: read only).
//
// A signed-in person asks a question (and says what is on their screen); Gemini understands it and asks for look-ups; the look-ups read
// the books AS THAT PERSON (their role's permissions) and Gemini words the answer. Nothing of the conversation is stored — only facts the
// person asks it to remember, in the company's own books (assistant_facts).
//
// The logic lives in ./handler.bundle.js — a self-contained build of the domain, adapter-postgres and adapter-gemini
// (`pnpm build:functions`). This file is only the Deno glue.
//
// Environment (the same secrets as `intake`):
//   SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, SUPABASE_DB_URL   provided by Supabase
//   GEMINI_API_KEY    an API key from Google AI Studio          supabase secrets set GEMINI_API_KEY=…
//   GEMINI_MODEL      the model(s) to ask, in order, comma-separated: a busy one hands over to the next

import { createClient } from '@supabase/supabase-js';
import postgres from 'postgres';
// @ts-expect-error — generated by `pnpm build:functions`; no type declarations
import { GeminiChat, PostgresBackend, createAssistantHandler } from './handler.bundle.js';

const sql = postgres(Deno.env.get('SUPABASE_DB_URL')!, { max: 1, prepare: false });
const db = {
  query: async (text: string, values: readonly unknown[] = []) => ({
    rows: (await sql.unsafe(text, values as never[])) as unknown as Record<string, unknown>[],
  }),
};

const admin = createClient(Deno.env.get('SUPABASE_URL')!, Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!, {
  auth: { persistSession: false },
});

const apiKey = Deno.env.get('GEMINI_API_KEY');
const model = Deno.env.get('GEMINI_MODEL');

Deno.serve(
  createAssistantHandler({
    async authenticate(request: Request) {
      const token = request.headers.get('Authorization')?.replace(/^Bearer\s+/i, '');
      if (!token) return undefined;
      const { data, error } = await admin.auth.getUser(token);
      return error || !data.user ? undefined : { userId: data.user.id };
    },
    gatewayFor: (actorId: string, requestId: string) => new PostgresBackend(db, { actorId, requestId }),
    chat:
      apiKey && model
        ? // a person is waiting: each model once, then once more after 2 s, within ~50 s in all
          new GeminiChat({ apiKey, model, timeoutMs: 30_000, rounds: 2, retryDelayMs: 2_000, deadlineMs: 50_000 })
        : { ask: async () => ({ ok: false, issues: [{ code: 'READER_NOT_SET_UP', message: 'Gemini is not set up: GEMINI_API_KEY and GEMINI_MODEL are needed' }] }) },
    // the error only — never the question, which may hold business details
    onError: (error: unknown, requestId: string) =>
      console.error(JSON.stringify({ level: 'error', requestId, error: String(error), stack: (error as Error)?.stack })),
  }),
);
