// Supabase Edge Function: post-voucher  (Deno runtime)
//
// The trusted write path into the books. The browser sends INTENT (a voucher draft); this function
// authenticates the caller, runs the same TypeScript domain code the browser uses to validate and plan
// the posting, then commits it through the atomic SQL functions (post_voucher_atomic and friends).
//
// The logic lives in ./handler.bundle.js — a self-contained build of packages/domain +
// packages/adapter-postgres (`pnpm build:functions`). This file is only the Deno glue:
// how to authenticate, and how to reach the database.
//
// Required environment (all provided automatically by Supabase):
//   SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, SUPABASE_DB_URL
// Optional, for emailing vouchers to their party through the company's Gmail (integrations/google-apps-script/SendVoucher.gs):
//   MAIL_SCRIPT_URL (the script's web-app /exec address) and MAIL_SCRIPT_SECRET (the same secret set in the script).
// The gateway verifies the caller's JWT before this code runs (verify_jwt = true, the default);
// we then resolve the user from it and act — and audit — as that user.

import { createClient } from '@supabase/supabase-js';
import postgres from 'postgres';
// @ts-expect-error — generated by `pnpm build:functions`; no type declarations
import { PostgresBackend, createPostingHandler } from './handler.bundle.js';

// One connection per function instance. `prepare: false` keeps it compatible with Supabase's
// transaction-mode connection pooler; each posting is a single statement, so it is one transaction.
const sql = postgres(Deno.env.get('SUPABASE_DB_URL')!, { max: 1, prepare: false });

const db = {
  query: async (text: string, values: readonly unknown[] = []) => ({
    rows: (await sql.unsafe(text, values as never[])) as unknown as Record<string, unknown>[],
  }),
};

const mailUrl = Deno.env.get('MAIL_SCRIPT_URL');
const mailSecret = Deno.env.get('MAIL_SCRIPT_SECRET');

/** Hands a voucher's mail to the Gmail script. Google answers a web-app POST with a redirect to the script's output, which fetch follows. */
async function sendMail(mail: Record<string, unknown>): Promise<{ ok: true } | { ok: false; message: string }> {
  try {
    const res = await fetch(mailUrl!, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ secret: mailSecret, ...mail }) });
    const text = await res.text();
    const answer = (() => {
      try {
        return JSON.parse(text) as { ok?: boolean; message?: string };
      } catch {
        return { ok: false, message: `the script answered ${res.status}` };
      }
    })();
    return answer.ok === true ? { ok: true } : { ok: false, message: answer.message ?? 'no reason given' };
  } catch (error) {
    return { ok: false, message: `could not reach the script (${String(error)})` };
  }
}

const admin = createClient(Deno.env.get('SUPABASE_URL')!, Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!, {
  auth: { persistSession: false },
});

Deno.serve(
  createPostingHandler({
    async authenticate(request: Request) {
      const token = request.headers.get('Authorization')?.replace(/^Bearer\s+/i, '');
      if (!token) return undefined;
      const { data, error } = await admin.auth.getUser(token);
      return error || !data.user ? undefined : { userId: data.user.id };
    },
    gatewayFor: (actorId: string, requestId: string) => new PostgresBackend(db, { actorId, requestId }),
    ...(mailUrl && mailSecret ? { sendMail } : {}),
    onError: (error: unknown, requestId: string) =>
      console.error(JSON.stringify({ level: 'error', requestId, error: String(error), stack: (error as Error)?.stack })),
  }),
);
